modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="godlikemod"
version="1.0.0"
displayName="Godlike Mod"
description="Adds a Godlike.host website button to the multiplayer screen."

[[dependencies.godlikemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"